/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package diet.server.conversation.ui;

import diet.server.Conversation;
import diet.server.Participant;
import diet.tg.TelegramParticipant;
import java.util.List;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author gj
 */
public class JInterventionsPanel  extends JPanel{

    Conversation c;
    boolean telegram;
    
    /**
     * Creates new form NewJPanel
     */
    public JInterventionsPanel() {
        initComponents();
    }
    
    
     public JInterventionsPanel(Conversation c, boolean telegram) {
        this.telegram=telegram;
         initComponents();
        this.c = c;
        if(telegram){
          jButton1.setVisible(false);
          jButton2.setVisible(false);
          jButton3.setVisible(false);
          jButton4.setVisible(false);
          jButton6.setVisible(false);
        }
        this.jTextArea1.setLineWrap(true);
        this.validate();
     }

     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Participant A (Apparent Origin)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(612, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(335, 130));
        jPanel1.setPreferredSize(new java.awt.Dimension(412, 130));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(500, 900));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 100));

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Block");
        jButton1.setEnabled(false);
        jButton1.setMaximumSize(new java.awt.Dimension(150, 130));
        jButton1.setMinimumSize(new java.awt.Dimension(150, 130));
        jButton1.setPreferredSize(new java.awt.Dimension(500, 70));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Unblock");
        jButton2.setEnabled(false);
        jButton2.setMaximumSize(new java.awt.Dimension(150, 130));
        jButton2.setMinimumSize(new java.awt.Dimension(150, 130));
        jButton2.setPreferredSize(new java.awt.Dimension(500, 70));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jPanel1.add(jPanel5, java.awt.BorderLayout.SOUTH);

        add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Participant B:  Recipient(s) of intervention", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(612, 900));
        jPanel2.setMinimumSize(new java.awt.Dimension(335, 130));
        jPanel2.setPreferredSize(new java.awt.Dimension(412, 130));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setMaximumSize(new java.awt.Dimension(300, 120));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(23, 120));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 120));

        jList2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList2.setMinimumSize(new java.awt.Dimension(33, 50));
        jList2.setPreferredSize(new java.awt.Dimension(33, 60));
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Block");
        jButton3.setEnabled(false);
        jButton3.setMaximumSize(new java.awt.Dimension(150, 120));
        jButton3.setMinimumSize(new java.awt.Dimension(150, 120));
        jButton3.setPreferredSize(new java.awt.Dimension(500, 70));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Unblock");
        jButton4.setEnabled(false);
        jButton4.setMaximumSize(new java.awt.Dimension(150, 120));
        jButton4.setMinimumSize(new java.awt.Dimension(150, 120));
        jButton4.setPreferredSize(new java.awt.Dimension(500, 70));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);

        jPanel2.add(jPanel6, java.awt.BorderLayout.SOUTH);

        add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message sent to B:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(612, 900));
        jPanel3.setMinimumSize(new java.awt.Dimension(335, 130));
        jPanel3.setPreferredSize(new java.awt.Dimension(412, 130));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setMaximumSize(new java.awt.Dimension(300, 120));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(23, 120));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(100, 120));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(164, 150));
        jScrollPane3.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Artificial typing");
        jButton6.setEnabled(false);
        jButton6.setMaximumSize(new java.awt.Dimension(150, 120));
        jButton6.setMinimumSize(new java.awt.Dimension(150, 120));
        jButton6.setPreferredSize(new java.awt.Dimension(500, 70));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Send message");
        jButton7.setEnabled(false);
        jButton7.setMaximumSize(new java.awt.Dimension(150, 120));
        jButton7.setMinimumSize(new java.awt.Dimension(150, 120));
        jButton7.setPreferredSize(new java.awt.Dimension(500, 70));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);

        jPanel3.add(jPanel4, java.awt.BorderLayout.SOUTH);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        this.validateButtons();
    }//GEN-LAST:event_jList2ValueChanged

    
    private Participant getParticipant(String guilistvalue){
        int apparentSenderidxOfComma = guilistvalue.indexOf(",");
        String apparentSenderUsernamepid = guilistvalue.substring(0, apparentSenderidxOfComma);
        Participant apparentSender = c.getParticipants().findParticipantWithEmail(apparentSenderUsernamepid);
        return apparentSender;
    }
    
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 try{
        System.err.println("Processing request");
        String message = jTextArea1.getText();
        List recipientsPIDUSERNAME = jList2.getSelectedValuesList();
        Vector v = new Vector(recipientsPIDUSERNAME);
        String apparentSenderUSERANDID = (String)jList1.getSelectedValue();
        //Participant apparentSender = c.getParticipants().findParticipantWithUsername(apparentSenderUsername);
        
        
        //c.sendArtificialTurnFromApparentOriginToRecipients(apparentSender, v, message);
        
        int apparentSenderidxOfComma = apparentSenderUSERANDID.indexOf(",");
        String apparentSenderUsernamepid = apparentSenderUSERANDID.substring(0, apparentSenderidxOfComma);
        Participant apparentSender = c.getParticipants().findParticipantWithEmail(apparentSenderUsernamepid);
        
        System.err.println("Apparent sender: Replacing "+ apparentSenderUSERANDID+" with "+apparentSenderUsernamepid);
        
        
        Vector vid = new Vector();
        for(int i=0;i<v.size();i++){
            String s = (String)v.elementAt(i);
            int idxOfComma = s.indexOf(",");
            String pid = s.substring(0, idxOfComma);
            System.err.println("Recipient(s): Replacing "+ s+" with "+pid);
            vid.add(pid);
        }
        
        
        if(telegram){

             c.telegram_sendArtificialTurnFromApparentOriginToParticipantID((TelegramParticipant)apparentSender, vid, message);
        }
        else{
             c.sendArtificialTurnFromApparentOriginToParticipantID(apparentSender, vid, message);     
        }
        
       
      }catch (Exception e){
          e.printStackTrace();
          Conversation.saveErr(e);
      }


// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String s = (String)jList2.getSelectedValue();
        System.err.println(s);
        Participant p = this.getParticipant(s);
        c.changeClientInterface_disableTextEntry(p);
        Conversation.printWSln("Main", s + " has text entry field blocked");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String s = (String)jList2.getSelectedValue();
        Participant p = this.getParticipant(s);
        c.changeClientInterface_enableTextEntry(p);
        Conversation.printWSln("Main", s + " has text entry field enabled");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String s = (String)jList1.getSelectedValue();
        Participant p = this.getParticipant(s);
        c.typingactivity_GenerateFakeTyping(p);
        Conversation.printWSln("Main", "Generated fake typing activity by "+s);
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String s = (String)jList1.getSelectedValue();
        Participant p = this.getParticipant(s);
        c.changeClientInterface_enableTextEntry(p);
        Conversation.printWSln("Main", s + " has text entry field enabled");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s = (String)jList1.getSelectedValue();
        Participant p = this.getParticipant(s);
        c.changeClientInterface_disableTextEntry(p);
        Conversation.printWSln("Main", s + " has text entry field blocked");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        this.validateButtons();

    }//GEN-LAST:event_jList1ValueChanged

    public void validateButtons(){
        if(jList1.getSelectedValue()==null){
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
        }
        else{
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
        
        }
        if(jList2.getSelectedValue()==null){
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
        }
        else{
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
        
        }
        if(jList2.getSelectedValue()!=null && jList2.getSelectedValue()!=null ){
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);
        }
        else{
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
        
        }
        
        
        
        
    }
    
    
    
     public void  updateParticipants(final Vector v){
        final Vector vNames = new Vector();
        for(int i=0;i<v.size();i++){
            String vName="";
            
            vName= ((Participant)v.elementAt(i)).getParticipantID();
            vName= vName +","+ ((Participant)v.elementAt(i)).getUsername();
            
            vNames.addElement(vName);
        }
        
        final JInterventionsPanel  jppi = this;
        SwingUtilities.invokeLater(new Runnable(){
            public void run(){
                jppi.jList1.setListData(vNames);
                jppi.jList2.setListData(vNames);
                repaint();
            }
         });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
