/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package diet.server.conversation.ui;

/**
 *
 * @author gj
 */
public class JPanelExtension extends javax.swing.JPanel {

    /**
     * Creates new form JPanel
     */
    public JPanelExtension() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Apparent Origin"));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(300, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 90));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setMinimumSize(new java.awt.Dimension(33, 50));
        jList1.setPreferredSize(new java.awt.Dimension(33, 60));
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);

        jButton1.setText("Block");
        jButton1.setMaximumSize(new java.awt.Dimension(150, 100));
        jButton1.setMinimumSize(new java.awt.Dimension(150, 100));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 100));
        add(jButton1);

        jButton2.setText("Unblock");
        jButton2.setMaximumSize(new java.awt.Dimension(150, 100));
        jButton2.setMinimumSize(new java.awt.Dimension(150, 100));
        jButton2.setPreferredSize(new java.awt.Dimension(150, 100));
        add(jButton2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
