/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diet.server.conversation.ui;

import diet.server.Conversation;
import diet.server.ConversationController.autointervention.interventionblock;
import diet.server.ConversationController.autointervention.interventiondelay;
import diet.server.ConversationController.autointervention.interventionmodify;
import java.awt.BorderLayout;
import java.util.Vector;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author LX1C
 */
public class JRulesBasedInterventions extends javax.swing.JPanel {

    Conversation c;
    JTabbedPane jtp = new JTabbedPane();
    
    
    JScrollPane jspB = new JScrollPane();
    JScrollPane jspM = new JScrollPane();
    JScrollPane jspD = new JScrollPane();
    
    /**
     * Creates new form JRulesBasedInterventions
     */
    public JRulesBasedInterventions(Conversation c) {
        initComponents();
        this.c=c;
        this.remove(jPanel5);
        jtp = new JTabbedPane();
        this.add(jtp,BorderLayout.CENTER);
        
        createPanels();
    }

    JRulesBasedInterventionsTableModelInterventionBlock jrbittmBLOCK;
    JRulesBasedInterventionsTableModelInterventionModify jrbittmMODIFY; 
    JRulesBasedInterventionsTableModelInterventionDelay jrbittmDELAY;
    
    public void createPanels(){
        Vector<interventionblock> ib =  c.ai.getBlockRules();
        JRulesBasedInterventionsTable jrbit = new JRulesBasedInterventionsTable(c);
        jrbittmBLOCK = new JRulesBasedInterventionsTableModelInterventionBlock(jrbit,c);
         jrbit.setModel(jrbittmBLOCK);
         jspB.getViewport().add(jrbit);    
         jtp.add(jspB,"Block");
         jrbittmBLOCK.refresh();
        
        
        Vector<interventionmodify> im =  c.ai.getModifyRules();
        JRulesBasedInterventionsTable jrbit2 = new JRulesBasedInterventionsTable(c);
        jrbittmMODIFY = new JRulesBasedInterventionsTableModelInterventionModify(jrbit2,c);
        jrbit2.setModel(jrbittmMODIFY);
        jspM.getViewport().add(jrbit2);        
        jtp.add(jspM,"Modify");
        jrbittmMODIFY.refresh();
        
        
        Vector<interventiondelay> id =  c.ai.getDelayRules();
        JRulesBasedInterventionsTable jrbit3 = new JRulesBasedInterventionsTable(c);
        jrbittmDELAY = new JRulesBasedInterventionsTableModelInterventionDelay(jrbit3,c);
        jrbit3.setModel(jrbittmDELAY);
        jspD.getViewport().add(jrbit3);    
        jtp.add(jspD,"Delay");
         jrbittmDELAY.refresh();
        
        
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 867, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("  "));
        jPanel1.setPreferredSize(new java.awt.Dimension(713, 90));

        jButton1.setText("load rules from spreadsheet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Note: as soon as the rules are loaded, they will be active. It is best practice to edit the rules in an external spreadsheet");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setPreferredSize(new java.awt.Dimension(10, 544));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel3.setPreferredSize(new java.awt.Dimension(713, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel4.setPreferredSize(new java.awt.Dimension(10, 544));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        add(jPanel4, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        c.ai.loadFromFile();
         jrbittmBLOCK.refresh();
        jrbittmMODIFY.refresh();
        jrbittmDELAY.refresh();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
