/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diet.tg;

import diet.server.Conversation;
import diet.server.experimentmanager.JExperimentManagerMainFrame;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.util.Date;

/**
 *
 * @author LX1C
 */
public class JTGSETUPUI extends javax.swing.JDialog {

    
    JExperimentManagerMainFrame parent;
    
    /**
     * Creates new form JTGSETUPUI
     */
    public JTGSETUPUI(JExperimentManagerMainFrame parent, boolean modal) {
        super(parent, modal);
        System.err.println("JTGHEREA");
        this.parent=parent;
        try{
             System.err.println("JTGHEREA1");
            initComponents();
             System.err.println("JTGHEREA2");
//             this.jTextArea2.setBackground(jPanel1.getBackground());
              System.err.println("JTGHEREA3");
             //this.setVisible(true);
              System.err.println("JTGHEREA4");
        }catch(Exception e){
            e.printStackTrace();
                    
        }
        System.err.println("JTGHEREB");
        
        
       
        
        System.err.println("JTGHEREC");
        String s = System.getProperty("user.dir");
        String tgdirectory = s+File.separator+ "tg";
        
         File fdir = new File(tgdirectory);    
         
         System.err.println("JTGHERED");
         if(fdir.exists()){
             System.err.println("JTGHEREE");
            jLabel4.setText("This option will backup the old folder and create a new folder called \"tg\" in the chattool folder");
            jLabel4.setForeground(Color.red);
            jLabel4.paintImmediately(jLabel4.getVisibleRect());
            jLabel4.repaint();
            this.validate();
            //System.exit(5);
         }
         else{
             System.err.println("JTGHEREF");
             jLabel4.setText("This option will create a new folder called \"tg\" in the chattool folder");
             jLabel4.paintImmediately(jLabel4.getVisibleRect());
             jLabel4.repaint();
             this.validate();
             //System.exit(6);
         }
         this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        setMaximumSize(new java.awt.Dimension(2147483647, 530));
        setPreferredSize(new java.awt.Dimension(550, 300));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter your Bot Credentials"));
        jPanel3.setMinimumSize(new java.awt.Dimension(450, 161));
        jPanel3.setPreferredSize(new java.awt.Dimension(450, 246));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(3, 1, 0, 3));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("To proceed you first need to register the chattool as a bot on the Telegram service");
        jPanel1.add(jLabel9);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("See the usermanual or https://core.telegram.org/bots#6-botfather ");
        jPanel1.add(jLabel8);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Registering a new bot takes less than 2 mins");
        jPanel1.add(jLabel10);

        jPanel3.add(jPanel1);

        jPanel6.setLayout(new java.awt.GridLayout());
        jPanel3.add(jPanel6);

        jPanel4.setMinimumSize(new java.awt.Dimension(54, 30));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Bot name ");
        jPanel4.add(jLabel1);

        jTextField1.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField1PropertyChange(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField1);

        jPanel3.add(jPanel4);

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 20));
        jPanel2.setPreferredSize(new java.awt.Dimension(848, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2);

        jPanel5.setMinimumSize(new java.awt.Dimension(53, 30));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Bot token ");
        jPanel5.add(jLabel2);

        jTextField2.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField2PropertyChange(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel5.add(jTextField2);

        jPanel3.add(jPanel5);

        jPanel9.setMaximumSize(new java.awt.Dimension(32767, 10));
        jPanel9.setPreferredSize(new java.awt.Dimension(350, 10));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel9);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("This option will backup the old folder and create a new folder called \\\"tg\\");

            javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
            jPanel10.setLayout(jPanel10Layout);
            jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 492, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
            );
            jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
            );

            jPanel3.add(jPanel10);

            jPanel7.setPreferredSize(new java.awt.Dimension(400, 28));
            jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

            jPanel8.setMaximumSize(new java.awt.Dimension(900, 32767));
            jPanel8.setPreferredSize(new java.awt.Dimension(250, 26));

            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

            javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
            jPanel8.setLayout(jPanel8Layout);
            jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(427, 427, 427))
            );
            jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            );

            jPanel7.add(jPanel8);

            jButton2.setText("CANCEL");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });
            jPanel7.add(jButton2);

            jButton1.setText(" SAVE ");
            jButton1.setEnabled(false);
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            jPanel7.add(jButton1);

            jPanel3.add(jPanel7);

            getContentPane().add(jPanel3);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    
    public void checkIfButtonIsOK(){
        if(jTextField1.getText().length()>4){
             if(jTextField2.getText().length()>4){
                  this.jButton1.setEnabled(true);
                  return;
             }
        }
        this.jButton1.setEnabled(false);
    }
    
    
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        checkIfButtonIsOK();
       
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        checkIfButtonIsOK();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.createNewFolder();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField1PropertyChange
        // TODO add your handling code here:
        checkIfButtonIsOK();
    }//GEN-LAST:event_jTextField1PropertyChange

    private void jTextField2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField2PropertyChange
        // TODO add your handling code here:
        checkIfButtonIsOK();
    }//GEN-LAST:event_jTextField2PropertyChange

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
         checkIfButtonIsOK();
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
         checkIfButtonIsOK();
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
         checkIfButtonIsOK();
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
         checkIfButtonIsOK();
    }//GEN-LAST:event_jTextField2KeyPressed

    
    public void createNewFolder(){
        
        Thread t = new Thread(){
            public void run(){
                String s = System.getProperty("user.dir");
                String tgdirectory = s+File.separator+ "tg";
                
                File fdir = new File(tgdirectory);
                
                
                if(fdir.exists()){
                   String newname = "tg_backup_"+new Date().getTime()+ "";
                   String fullnewname = s + File.separator+newname;
                   File fullnewnamefile = new File(newname);
                   try{
                       boolean renamed = fdir.renameTo(fullnewnamefile);
                       if(renamed){
                           parent.displayTextOutputInBottomTextarea("Main", "\nBacked up old telegram folder\n");
         
                       }
                   }catch(Exception e){
                       e.printStackTrace();
                       parent.displayTextOutputInBottomTextarea("Main", "\nCould not rename the old folder - please delete/rename it manually - please read the user manual for instructions!\n");
                   }
                    
                   
                }
                
                     try{
                         boolean created = fdir.mkdir();
                         if(!created){
                             parent.displayTextOutputInBottomTextarea("Main", "Could not create new folder:\n\n"+tgdirectory);
                             
                             //CustomDialog.showDialog("Could not create new folder:\n\n"+tgdirectory);
                             dispose();
                             return;
                         }
                          parent.displayTextOutputInBottomTextarea("Main",  "\nCreated new telegram directory in: "+tgdirectory+"\n");
                         
                     }catch(Exception e){
                         e.printStackTrace();
                     }
                
                
                File f = new File(fdir,"botname.txt");
                
                try{
                    BufferedWriter out = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(f), "UTF-8"));
                    out.write(jTextField1.getText()+"\n");
                    out.write(jTextField2.getText()+"\n");
                    out.close();
                     parent.displayTextOutputInBottomTextarea("Main",  "\nCreated new file: "+f.getName()+ " with bot settings\n");
                } catch (Exception e){
                    e.printStackTrace();
                     parent.displayTextOutputInBottomTextarea("Main",  "\nCould not create and write to file botname.txt\n");
                    Conversation.saveErr(e);
                } 
                

                
                
                
                
            }
        };
        t.start();
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTGSETUPUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTGSETUPUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTGSETUPUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTGSETUPUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JTGSETUPUI dialog = new JTGSETUPUI(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
