/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diet.task.CustomizableReferentialTask;

import diet.server.Conversation;
import java.awt.Color;
import java.awt.image.BufferedImage;
import javax.swing.SwingUtilities;
import javax.swing.border.TitledBorder;

/**
 *
 * @author LX1C
 */
public class JCustomizableReferentialTask extends javax.swing.JPanel {

    CustomizableReferentialTask crt;
    
    JCustomizableReferentialTaslkImagePanel jLeft ;
    JCustomizableReferentialTaslkImagePanel jRight;
    
    /**
     * Creates new form JCustomizableReferentialTask
     */
    public JCustomizableReferentialTask() {
        initComponents();
    }

    /**
     * Creates new form JCustomizableReferentialTask
     */
    public JCustomizableReferentialTask( CustomizableReferentialTask crt) {
        this.crt = crt;
        initComponents();
        
          jLeft = new JCustomizableReferentialTaslkImagePanel();
          jRight = new JCustomizableReferentialTaslkImagePanel();
          
          this.jTabbedPane1.addTab("Participant1", jLeft);
          this.jTabbedPane2.addTab("Participant2", jRight);
          
         
          
    
        
    }
    
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEast = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jPanelCENTRE = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel6 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jPanelWest = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanelEast.setLayout(new javax.swing.BoxLayout(jPanelEast, javax.swing.BoxLayout.Y_AXIS));

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(900, 900));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(300, 200));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanelEast.add(jTabbedPane1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jPanelEast.add(jLabel1);

        add(jPanelEast);

        jPanelCENTRE.setMaximumSize(new java.awt.Dimension(300, 900));
        jPanelCENTRE.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanelCENTRE.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanelCENTRE.setLayout(new javax.swing.BoxLayout(jPanelCENTRE, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setPreferredSize(new java.awt.Dimension(285, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Participant Group");
        jLabel7.setMaximumSize(new java.awt.Dimension(85, 10));
        jLabel7.setPreferredSize(new java.awt.Dimension(85, 10));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanelCENTRE.add(jPanel4);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(32767, 13000));
        jScrollPane2.setName(""); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 300));
        jScrollPane2.setViewportView(jTextPane2);

        jPanelCENTRE.add(jScrollPane2);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel8.setMaximumSize(new java.awt.Dimension(411, 50));
        jPanel8.setMinimumSize(new java.awt.Dimension(0, 50));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("[SAME] [DIFFERENT]");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanelCENTRE.add(jPanel8);

        jPanel7.setMaximumSize(new java.awt.Dimension(98301, 90));
        jPanel7.setMinimumSize(new java.awt.Dimension(300, 90));
        jPanel7.setPreferredSize(new java.awt.Dimension(278, 90));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Participant", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel9.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel3.setText("Correct:");

        jLabel4.setText("Incorrect:");

        jLabel17.setText("100");

        jLabel18.setText("100");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel17))
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel18)))
        );

        jPanel7.add(jPanel9);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel5);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dyad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel10.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel10.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel10.setText("Game: ");

        jLabel12.setText("Timeout:");

        jLabel19.setText("100");

        jLabel20.setText("100");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19))
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel20)))
        );

        jPanel7.add(jPanel10);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel3);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Participant2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel12.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel6.setText("Correct:");

        jLabel9.setText("Incorrect:");

        jLabel13.setText("100");

        jLabel15.setText("100");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addGap(10, 10, 10)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15)))
        );

        jPanel7.add(jPanel12);
        jPanel7.add(filler1);

        jPanelCENTRE.add(jPanel7);

        jPanel6.setMaximumSize(new java.awt.Dimension(32889, 20));
        jPanel6.setMinimumSize(new java.awt.Dimension(132, 20));
        jPanel6.setPreferredSize(new java.awt.Dimension(203, 20));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jToggleButton1.setText("PAUSE");
        jPanel6.add(jToggleButton1);

        jProgressBar1.setMaximumSize(new java.awt.Dimension(32767, 20));
        jProgressBar1.setMinimumSize(new java.awt.Dimension(10, 20));
        jProgressBar1.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel6.add(jProgressBar1);

        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);

        jPanelCENTRE.add(jPanel6);

        add(jPanelCENTRE);

        jPanelWest.setLayout(new javax.swing.BoxLayout(jPanelWest, javax.swing.BoxLayout.Y_AXIS));

        jTabbedPane2.setMaximumSize(new java.awt.Dimension(900, 900));
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(300, 5));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanelWest.add(jTabbedPane2);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        jPanelWest.add(jLabel2);

        add(jPanelWest);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.jumpToNext=true;
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelCENTRE;
    private javax.swing.JPanel jPanelEast;
    private javax.swing.JPanel jPanelWest;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables


public void setLeftParticipantName(String participantID, String username){
    SwingUtilities.invokeLater(new Runnable(){
      public void run(){
          jTabbedPane1.setTitleAt(0, participantID +","+username);
           //TitledBorder tb = (TitledBorder) jPanel9.getBorder();
           //tb.setTitle(username);
           jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, participantID+": "+username, javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
            validate();
           
           
      }
   });  
    
   
         
    
}
public void setRightParticipantName(String participantID, String username){
    SwingUtilities.invokeLater(new Runnable(){
      public void run(){
          jTabbedPane2.setTitleAt(0, participantID +","+username);
           //TitledBorder tb = (TitledBorder) jPanel12.getBorder();
           //tb.setTitle(username);
           //tb.setTitleColor(Color.red);
            jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, participantID+": "+username, javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        
           validate();
           
      }
   });  
    
}
public void setLeftreferentName(String s){
   SwingUtilities.invokeLater(new Runnable(){
      public void run(){
          jLabel1.setText(s);
      }
   });   
}
public void setRightreferentName(String s){
     SwingUtilities.invokeLater(new Runnable(){
      public void run(){
          jLabel2.setText(s);
      }
   });   
}


public void setTimeoutLabel(String s){
    System.err.println("1.SETTING LABEL20 TO "+s);
     SwingUtilities.invokeLater(new Runnable(){
      public void run(){
           jLabel20.setText(s);
           System.err.println("2. SETTING LABEL20 TO "+s);
      }
   }); 
   
}
public void setGameNoLabel(String gameNo){
    SwingUtilities.invokeLater(new Runnable(){
      public void run(){
          jLabel19.setText(gameNo);
      }
   });   
   
}
public void setLeftCorrectLabel(String s){
    SwingUtilities.invokeLater(new Runnable(){
      public void run(){
          jLabel17.setText(s);
      }
   });    
}
public void setLeftIncorrectLabel(String s){
   SwingUtilities.invokeLater(new Runnable(){
      public void run(){
           jLabel18.setText(s);
      }
   }); 
}

public void setRightCorrectLabel(String s){
    SwingUtilities.invokeLater(new Runnable(){
      public void run(){
          jLabel13.setText(s);
      }
   });    
}
public void setRightIncorrectLabel(String s){
   SwingUtilities.invokeLater(new Runnable(){
      public void run(){
           jLabel15.setText(s);
      }
   }); 
}



public void setOptionsDEPRECATED(String s){
     SwingUtilities.invokeLater(new Runnable(){
      public void run(){
           jLabel8.setText(s);
      }
   }); 
   
}

public void setOptions(String options[], String[] corrects){
    String menu = "";
    
    for (int i=0;i<options.length;i++){
        String option = options[i];
        boolean iscorrect = false;
        for(int j=0;j<corrects.length;j++){
            String correct = corrects[j];
            if(option.equals(correct)){
                iscorrect = true;
                break;
            }
        }
        if(!iscorrect)menu=menu+" "+ option;
        else if(iscorrect)menu=menu+ " "+ "["+option+"]";
    }
    final String newmenu = menu;
    
     SwingUtilities.invokeLater(new Runnable(){
      public void run(){
           jLabel8.setText(newmenu);
      }
   }); 
    
}





public void setParticipantGroup(String s){
     SwingUtilities.invokeLater(new Runnable(){
      public void run(){
           jLabel7.setText(s);
      }
   }); 
   
}

public void changeJProgressBar(String timeRemainingSeconds, int percentage, Color col){
     SwingUtilities.invokeLater(new Runnable(){
      public void run(){
           jProgressBar1.setValue((int)percentage);
           jProgressBar1.setString(timeRemainingSeconds+"");
           jProgressBar1.setForeground(col);
           jProgressBar1.setStringPainted(true);
      }
   }); 
   
   
}

public void setLeftImageName(String s){
    System.err.println("SETLEFTBUFFEREDIMAGE");
    SwingUtilities.invokeLater(new Runnable(){
      public void run(){
          jLabel1.setText(s);
      }
    });
}

public void setrightImageName(String s){
    System.err.println("SETLEFTBUFFEREDIMAGE");
    SwingUtilities.invokeLater(new Runnable(){
      public void run(){
          jLabel2.setText(s);
      }
    });
}



public void setLeftBufferedImage(BufferedImage bi){
    System.err.println("SETLEFTBUFFEREDIMAGE");
    SwingUtilities.invokeLater(new Runnable(){
      public void run(){
          jLeft.setBufferedImage(bi);
      }
    });
}

public void setRightBufferedImage(BufferedImage bi){
    System.err.println("SETRIGHTBUFFEREDIMAGE");
    SwingUtilities.invokeLater(new Runnable(){
      public void run(){
          jRight.setBufferedImage(bi);
      }
    });
}

public void processChatText(String username, String text){
    int length = this.jTextPane2.getDocument().getLength();
    String insertstring = username+": "+text+"\n"; 
    SwingUtilities.invokeLater(new Runnable(){
      public void run(){
          try{
            jTextPane2.getDocument().insertString(length, insertstring, null);
          }catch(Exception e){
              e.printStackTrace();
              Conversation.saveErr(e);
          }  
      }
    });
    
    
}

public boolean isPausePressed(){
    return this.jToggleButton1.isSelected();
}

boolean jumpToNext = false;
public boolean goToNext(){
    if(jumpToNext){
        this.jumpToNext=false;
        return true;
    }
    return false;
}



}
