/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diet.server.ParticipantGroups.ui;

import diet.server.Conversation;
import diet.server.Participant;
import diet.server.ParticipantGroups.ParticipantGroups;
import diet.utils.VectorHashtable;
import java.util.Set;
import java.util.Vector;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author LX1C
 */
public class JPanelConfig extends javax.swing.JPanel {

    
    JScrollPane jScrollPaneDyad = new JScrollPane();
    JScrollPane jScrollPaneTriad = new JScrollPane();
    JScrollPane jScrollPaneQuad = new JScrollPane();
    
    
    JPanelConfigurationDyadInC8Table  jpcdt;//= new JPanelConfigurationdyadTable();
    JPanelConfigurationTriadTable  jpcdtt;//= new JPanelConfigurationtriadTable();
     JPanelConfigurationQuadTable  jpcdqt;//= new JPanelConfigurationtriadTable();
    
    JCustom jc ;//= new JCustom();
    
    ParticipantGroups pp;
    /**
     * Creates new form JPanelConfig
     */
    public JPanelConfig(ParticipantGroups pp) {
        this.pp = pp; 
        initComponents();
        
        jc= new JCustom(this);
             
        
        jpcdt= new JPanelConfigurationDyadInC8Table(pp.c);
        jpcdtt= new JPanelConfigurationTriadTable();
        jpcdqt= new JPanelConfigurationQuadTable(pp.c);
        
        
        
        
        
        jScrollPaneDyad.getViewport().add(jpcdt);
        jScrollPaneTriad.getViewport().add(jpcdtt);
        jScrollPaneQuad.getViewport().add(jpcdqt);
        
        
       
        jTabbedPane1.addTab("Dyads in communities of 8", jScrollPaneDyad);
        jTabbedPane1.addTab("Triads in communities of 6", jScrollPaneTriad);
        
        jTabbedPane1.addTab("Quads in communities of 8" , jScrollPaneQuad);
        
        jTabbedPane1.addTab("Custom", jc);
        
        
        
    }

    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        southpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(590, 300));
        setLayout(new java.awt.BorderLayout());

        northpanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Group configurations"));
        northpanel.setMinimumSize(new java.awt.Dimension(17, 50));
        northpanel.setPreferredSize(new java.awt.Dimension(100, 50));
        northpanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(396, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Use this option to assign participants to different sub-groups");
        jLabel1.setMaximumSize(new java.awt.Dimension(331, 10000));
        jLabel1.setMinimumSize(new java.awt.Dimension(331, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(331, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        northpanel.add(jPanel1, java.awt.BorderLayout.NORTH);
        northpanel.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        add(northpanel, java.awt.BorderLayout.CENTER);

        southpanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Assign participants to groups"));
        southpanel.setMinimumSize(new java.awt.Dimension(0, 70));
        southpanel.setPreferredSize(new java.awt.Dimension(400, 70));
        southpanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setMinimumSize(new java.awt.Dimension(100, 80));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 80));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.WEST);

        southpanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        jButton1.setText("CREATE GROUPS");
        jButton1.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(0, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        southpanel.add(jButton1, java.awt.BorderLayout.EAST);

        add(southpanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Object o =this.jTabbedPane1.getSelectedComponent();
        
        int seli = this.jTabbedPane1.getSelectedIndex();
        
        System.err.println(o.getClass().toString());
       // if(2<5) System.exit(56);
        
        Vector<String> vs = new Vector();
        if(seli==0){
              vs = this.jpcdt.getSelection();
              System.err.println("jb1SEL1");
        }
        else if(seli==1){
               vs = this.jpcdtt.getSelection();
               System.err.println("jb1SEL2");

        }
        else if(seli==2){
              vs = this.jpcdqt.getSelection();
              System.err.println("jb1SEL3");
        }
        
        else if(seli==3){
              vs = this.jc.getSelection();
              System.err.println("jb1SEL4");
        }
        
        Vector<Participant> allp = this.pp.c.getParticipants().getAllParticipants();
        
        VectorHashtable ht = new VectorHashtable();
        
        try{
        for(int i=0;i<allp.size(); i++){
            Participant p = allp.elementAt(i);
            String newGroup = vs.elementAt(i);
            ht.put(newGroup, p);
            System.err.println("Assigning "+p.getUsername()+  " to "+newGroup);
        }
        
        Set s = ht.getAllKeys();
        Object[] sA = s.toArray();
        for(int i=0;i<sA.length;i++){
              Vector v = ht.get(sA[i]);
              String name = (String)sA[i];
              this.pp.createNewSubdialogue(name, v);
              
        }
        
        
        
       
        
        
        }catch(Exception e){
            e.printStackTrace();
            Conversation.saveErr(e);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel northpanel;
    private javax.swing.JPanel southpanel;
    // End of variables declaration//GEN-END:variables


   public void updateData(){
        SwingUtilities.invokeLater(new Runnable(){
           public void run(){
                jpcdt.updateData();      
           }
        });
   }


}
