/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diet.server.ParticipantGroups.ui;

import diet.server.ParticipantGroups.ParticipantGroups;

/**
 *
 * @author LX1C
 */
public class JPanelCurrentGroupsAndConfiguration extends javax.swing.JPanel {

    ParticipantGroups pp;
    JPanelCurrentGroups jpcg;
    JPanelConfig jpc;
    
    
    /**
     * Creates new form JPanelCurrentGroupAndConfiguration
     */
    public JPanelCurrentGroupsAndConfiguration(ParticipantGroups pp) {
        initComponents();
        this.pp=pp;
        
        
        this.jpcg=new JPanelCurrentGroups(pp);      
        //this.add(jpcg);
        this.jSplitPane1.setLeftComponent(jpcg);
        
        
        
        this.jpc=new  JPanelConfig(pp);
         this.jSplitPane1.setRightComponent(jpc);
        //this.add(jpc );
        
        
        this.jSplitPane1.setDividerLocation((double)0.3);
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables


  public void updateData(){
      jpcg.updateData();
      jpc.updateData();
  }



}
